export const card = [
    {
        id: 1, 
        name:"Introduction",
        cards: [
            {romanji:'shuusshin', meaning:'hometown'}, {romanji:'kyoushi/sensei', meaning:'teacher'},
            {romanji:'gakusei', meaning:'student'}, {romanji:'untenshu', meaning:'driver'},
            {romanji:'kaishain', meaning:'workman'}, {romanji:'ginkouin', meaning:'banker'},
            {romanji:'isha', meaning:'doctor'}, {romanji:'enjinia', meaning:'engineer'},
            {romanji:'kenkyuusha', meaning:'scientist'}, {romanji:'ryuugakusei', meaning:'oversea student'},
            {romanji:'daigaku', meaning:'university'}, {romanji:'byouin', meaning:'hospital'},
            {romanji:'nihon', meaning:'japan'}, {romanji:'betonamu', meaning:'vietnam'},
            {romanji:'kankoku', meaning:'korea'}, {romanji:'chuugoku', meaning:'china'},
            {romanji:'igirisu', meaning:'england'}, {romanji:'doitsu', meaning:'german'},
      ]
    },
    {
        id: 2, 
        name:"This is my bag",
        cards: [
            {romanji:'pasokon', meaning:'PC'}, {romanji:'keitai', meaning:'mobile phone'},
            {romanji:'aifuon', meaning:'iphone'}, {romanji:'denwa', meaning:'phone'},
            {romanji:'chuudenki', meaning:'charger'}, {romanji:'heddofuon', meaning:'headphone'},
            {romanji:'kamera', meaning:'camera'}, {romanji:'terebi', meaning:'television'},
            {romanji:'kuruma', meaning:'car'}, {romanji:'tokei', meaning:'clock, watch'},
            {romanji:'pen', meaning:'pen'}, {romanji:'bo-rupen', meaning:'ball pen'},
            {romanji:'enpitsu', meaning:'pencil'}, {romanji:'sha-pupenshiru', meaning:'metal pencil'},
            {romanji:'keshigomu', meaning:'eraser'}, {romanji:'hon', meaning:'book'},
            {romanji:'no-to', meaning:'notebook'}, {romanji:'techou', meaning:'handbook'},
            {romanji:'jisho', meaning:'dictionary'}, {romanji:'shinbun', meaning:'newspaper'},
            {romanji:'zasshi', meaning:'margazine'}, {romanji:'meishi', meaning:'cardvisit'},
            {romanji:'ca-do', meaning:'card'}, {romanji:'kurejitto ca-do', meaning:'credit card'},
            {romanji:'boshi', meaning:'hat'}, {romanji:'saifu', meaning:'wallet'},
            {romanji:'kaban', meaning:'bag'}, {romanji:'kutsu', meaning:'shoes'},
            {romanji:'surippa', meaning:'slipper'}, {romanji:'kutsushita', meaning:'socks'},
            {romanji:'kaigi', meaning:'key'}, {romanji:'kasa', meaning:'umbrella'},
            {romanji:'isu', meaning:'table'}, {romanji:'tsukue', meaning:'chair'},
      ]
    },
    {
        id: 3, 
        name:"This is my school",
        cards: [
            {romanji:'uketsuke', meaning:'reception (for company)'}, {romanji:'furonto', meaning:'reception (for hotel)'},
            {romanji:'kaidan', meaning:'stairs'}, {romanji:'erebe-ta-', meaning:'elevator'},
            {romanji:'esukare-ta-', meaning:'escalator'}, {romanji:'otearai/ toire', meaning:'toilet'},
            {romanji:'uchi/ie', meaning:'home'}, {romanji:'heya', meaning:'room'},
            {romanji:'kyoushitsu', meaning:'classroom'}, {romanji:'jimusho', meaning:'ofice'},
            {romanji:'kaigishitsu', meaning:'meeting room'}, {romanji:'shokudou', meaning:'diningroom'},
            {romanji:'biru', meaning:'building'}, {romanji:'depa-to', meaning:'mall'},
            {romanji:'su-pa-', meaning:'supermarket'}, {romanji:'centa-', meaning:'center area'},
            {romanji:'eigakan', meaning:'movie theater'}, {romanji:'kissaten', meaning:'cafeteria'},
            {romanji:'toshokan', meaning:'library'}, {romanji:'kaisha', meaning:'company'},
            {romanji:'gakkou', meaning:'school'}, {romanji:'yuubinkyoku', meaning:'post office'},
            {romanji:'ginkou', meaning:'bank'}, {romanji:'basutei', meaning:'bus stop'},
            {romanji:'kuni', meaning:'country'}, {romanji:'ikura', meaning:'how much money?'},
            {romanji:'eki', meaning:'station'},
      ]
    },
    {
        id: 4, 
        name:"I'm handsome",
        cards: [
            {romanji:'ikemen[na]', meaning:'handsome'}, {romanji:'kirei[na]', meaning:'pretty, clean, beautiful'},
            {romanji:'shinsetsu[na]', meaning:'kind'}, {romanji:'genki[na]', meaning:'strong'},
            {romanji:'shizuka[na]', meaning:'quiet'}, {romanji:'nigiyaka[na]', meaning:'noisy'},
            {romanji:'yuumei[na]', meaning:'famous'}, {romanji:'benri[na]', meaning:'convenient'},
            {romanji:'taisetsu[na]', meaning:'importance'}, {romanji:'hima[na]', meaning:'free'},
            {romanji:'isogashii', meaning:'busy'}, {romanji:'ookii', meaning:'big'},
            {romanji:'chisai', meaning:'small'}, {romanji:'atarashii', meaning:'new'},
            {romanji:'furui', meaning:'old'}, {romanji:'ii', meaning:'good'},
            {romanji:'warui', meaning:'bad'}, {romanji:'atsui', meaning:'hot'},
            {romanji:'samui', meaning:'cold(for weather)'}, {romanji:'tsumetai', meaning:'cold(for feeling)'},
            {romanji:'muzukashii', meaning:'difficult'}, {romanji:'yasashii', meaning:'easy'},
            {romanji:'takai', meaning:'tall, expensive'}, {romanji:'yasui', meaning:'cheap'},
            {romanji:'hikui', meaning:'short'}, {romanji:'akarui', meaning:'bright'},
            {romanji:'kurai', meaning:'dark'}, {romanji:'omoshiroi', meaning:'interesting'},
            {romanji:'kawaii', meaning:'cute'}, {romanji:'oishii', meaning:'delicous'},
            {romanji:'tanoshii', meaning:'fun'}, {romanji:'shiroi', meaning:'white'},
            {romanji:'akai', meaning:'red'}, {romanji:'aoi', meaning:'blue'},
            {romanji:'kuroi', meaning:'black'}, {romanji:'sakura', meaning:'cherry blossom'},
            {romanji:'yama', meaning:'moutain'}, {romanji:'machi', meaning:'town'},
            {romanji:'tabemono', meaning:'food'}, {romanji:'kimono', meaning:'kimono'},
            {romanji:'kikai', meaning:'machine'}, {romanji:'tokoro', meaning:'place'},
            {romanji:'benkyou', meaning:'study'}, {romanji:'seikatsu', meaning:'live'},
            {romanji:'bukka', meaning:'price'}, {romanji:'pasupo-to', meaning:'passport'},
      ]
    },
    {
        id:5,
        name:"what time?",
        cards:[
            {romanji:"getsuyoubi", meaning: "monday"}, {romanji:"kayoubi", meaning: "tuesday"},
            {romanji:"suiyoubi", meaning: "wednesday"}, {romanji:"mokuyoubi", meaning: "thursday"},
            {romanji:"kinyoubi", meaning: "friday"}, {romanji:"douyoubi", meaning: "saturday"},
            {romanji:"nichiyoubi", meaning: "sunday"}, {romanji:"ima", meaning: "now"},
            {romanji:"han", meaning: "30 minutes, half"}, {romanji:"gozen", meaning: "before noon"},
            {romanji:"gogo", meaning: "after noon"}, {romanji:"asa", meaning: "morning"},
            {romanji:"hiru", meaning: "noon"}, {romanji:"yugata", meaning: "afternoon"},
            {romanji:"ban", meaning: "night"}, {romanji:"yoru", meaning: "midnight"},
            {romanji:"ototoi", meaning: "2 days before"}, {romanji:"kinou", meaning: "yesterday"},
            {romanji:"kiyou", meaning: "today"}, {romanji:"ashita", meaning: "tomorrow"},
            {romanji:"asatte", meaning: "2 days after"}, {romanji:"kesa", meaning: "this morning"},
            {romanji:"konban", meaning: "this night"}, {romanji:"konya", meaning: "this midnight"},
            {romanji:"yasumi", meaning: "rest"}, {romanji:"kesa", meaning: "this morning"},
            {romanji:"hararaku/hatarakimasu", meaning: "work"}, {romanji:"yasumu/yasumimasu", meaning: "rest"},
            {romanji:"owaru/owarimasu", meaning: "finish"}, {romanji:"okiru/okimasu", meaning: "get up"},
            {romanji:"neru/nemasu", meaning: "go to sleep"}, {romanji:"benkyosuru/benkyoushimasu", meaning: "study"},
            {romanji:"shiken", meaning: "test"}, {romanji:"kaigi", meaning: "meeting"},
        ]
    },
    {
        id:6,
        name:"Today is my birthday",
        cards:[
            {romanji:"hikouki", meaning: "plane"}, {romanji:"fune", meaning: "boat"},
            {romanji:"chikatetsu", meaning: "subway"}, {romanji:"densha", meaning: "metro"},
            {romanji:"baiku", meaning: "motorbike"}, {romanji:"basu", meaning: "bus"},
            {romanji:"takushi-", meaning: "cab"}, {romanji:"jitensha", meaning: "bike"},
            {romanji:"aruite", meaning: "walk"}, {romanji:"hoteru", meaning: "hotel"},
            {romanji:"bijuutsukan", meaning: "art museum"}, {romanji:"tomodachi", meaning: "friend"},
            {romanji:"hitoride", meaning: "alone"}, {romanji:"kazoku", meaning: "family"},
            {romanji:"senshuu", meaning: "last week"}, {romanji:"konshuu", meaning: "this week"},
            {romanji:"raishuu", meaning: "next week"}, {romanji:"sengetsu", meaning: "last month"},
            {romanji:"kongetsu", meaning: "this month"}, {romanji:"raigetsu", meaning: "next month"},
            {romanji:"kyonen", meaning: "last year"}, {romanji:"kotoshi", meaning: "this year"},
            {romanji:"rainen", meaning: "next year"}, {romanji:"tsuitachi", meaning: "1st day"},
            {romanji:"futsuka", meaning: "2nd day"}, {romanji:"mikka", meaning: "3rd"},
            {romanji:"yokka", meaning: "4th day"}, {romanji:"itsuka", meaning: "5th day"},
            {romanji:"muika", meaning: "6th day"}, {romanji:"nanoka", meaning: "7th day"},
            {romanji:"youka", meaning: "8th day"}, {romanji:"kokonoka", meaning: "9th day"},
            {romanji:"tooka", meaning: "10th day"}, {romanji:"juuyokka", meaning: "14th day"},            
            {romanji:"hatsuka", meaning: "20th day"}, {romanji:"nijuuyokka", meaning: "24th day"},            
            {romanji:"tanjoubi", meaning: "birthday"}, {romanji:"nikki", meaning: "diary"},            
            {romanji:"honsha", meaning: "HeadQuarter"}, {romanji:"kuukou", meaning: "airport"},            
        ]
    },
    {
        id:7,
        name:"What do we eat?",
        cards:[
            {romanji:"chokore-to", meaning: "chocolate"}, {romanji:"pan", meaning: "bread"},
            {romanji:"gohan", meaning: "rice"}, {romanji:"tamago", meaning: "egg"},
            {romanji:"niku", meaning: "meat"}, {romanji:"gyuuniku", meaning: "beef"},
            {romanji:"sakana", meaning: "fish"}, {romanji:"yasai", meaning: "vegetable"},
            {romanji:"kudamono", meaning: "fruit"}, {romanji:"mizu", meaning: "water"},
            {romanji:"ocha", meaning: "tea"}, {romanji:"ko-hi-", meaning: "coffee"},
            {romanji:"wain", meaning: "wine"}, {romanji:"ju-su", meaning: "juice"},
            {romanji:"bi-ru", meaning: "beer"}, {romanji:"osake", meaning: "alcohol"},
            {romanji:"tabako", meaning: "cigarrette"}, {romanji:"kusuri", meaning: "drug"},
            {romanji:"tegami", meaning: "letter"}, {romanji:"me-ru", meaning: "mail"},
            {romanji:"repo-to", meaning: "report"}, {romanji:"comento", meaning: "comment"},
            {romanji:"ongaku", meaning: "music"}, {romanji:"eiga", meaning: "movie"},
            {romanji:"shashin", meaning: "picture"}, {romanji:"shukudai", meaning: "homework"},
            {romanji:"tenisu", meaning: "tennis"}, {romanji:"sakka-", meaning: "soccer"},
            {romanji:"[o]hanami", meaning: "flower-seeing"}, {romanji:"niwa", meaning: "garden"},
            {romanji:"mise", meaning: "shop"}, {romanji:"shougatsu", meaning: "new year"},
            {romanji:"yomu/yomimasu", meaning: "read"}, {romanji:"kaku/kakimasu", meaning: "write"},            
            {romanji:"kau/kaimasu", meaning: "buy"}, {romanji:"toru/torimasu", meaning: "take a photo"},            
            {romanji:"kiku/kikimasu", meaning: "hear"}, {romanji:"suru/shimasu", meaning: "do"},            
            {romanji:"suu/suimasu", meaning: "smoke"}, {romanji:"au/aimasu", meaning: "meet"},            
            {romanji:"nomu/nomimasu", meaning: "drink"}, {romanji:"taberu/tabemasu", meaning: "eat"},            
            {romanji:"miru/mimasu", meaning: "see"}, {romanji:"shokujisuru/shokujishimasu", meaning: "have dinner"},            
            {romanji:"isshoni", meaning: "together"}, {romanji:"chotto", meaning: "a little"},            
            {romanji:"itsumo", meaning: "always"}, {romanji:"tokidoki", meaning: "sometimes"},            
        ]
    },
    {
        id:8,
        name:"Give and take",
        cards:[
            {romanji:"maishuu", meaning: "every week"}, {romanji:"maitsuki", meaning: "every month"},
            {romanji:"maitoshi", meaning: "every year"}, {romanji:"te", meaning: "hand"},
            {romanji:"hashi", meaning: "chopstick"}, {romanji:"supo-n", meaning: "spoon"},
            {romanji:"fuo-ku", meaning: "fork"}, {romanji:"naifu", meaning: "knife"},
            {romanji:"hasami", meaning: "scissors"}, {romanji:"kami", meaning: "paper"},
            {romanji:"hasami", meaning: "scissors"}, {romanji:"kami", meaning: "paper"},
            {romanji:"hana", meaning: "flower"}, {romanji:"shatsu", meaning: "shirt"},
            {romanji:"purezento", meaning: "present"}, {romanji:"kippu", meaning: "ticket"},
            {romanji:"purezento", meaning: "present"}, {romanji:"kippu", meaning: "ticket"},
            {romanji:"ochawan", meaning: "cup"}, {romanji:"okane", meaning: "money"},
            {romanji:"ochawan", meaning: "cup"}, {romanji:"okane", meaning: "money"},
            {romanji:"kiru/kirimasu", meaning: "cut"}, {romanji:"okuru/okurimasu", meaning: "send"},
            {romanji:"morau/moraimasu", meaning: "receive"}, {romanji:"narau/naraimasu", meaning: "study"},
            {romanji:"kasu/kashimasu", meaning: "lend"}, {romanji:"ageru/agemasu", meaning: "give"},
            {romanji:"oshieru/oshiemasu", meaning: "teach"}, {romanji:"kakeru/kakemasu", meaning: "call"},
            {romanji:"kariru/karimasu", meaning: "borrow"}, {romanji:"mada", meaning: "not yet"},
            {romanji:"koibito", meaning: "lover"},
        ]
    },
    {
        id:9,
        name:"I love Japan",
        cards:[
            {romanji:"suki", meaning: "like"}, {romanji:"kirai", meaning: "hate"},
            {romanji:"jouzu", meaning: "good"}, {romanji:"heta", meaning: "bad"},
            {romanji:"itai", meaning: "painful"}, {romanji:"haisha", meaning: "dentist"},
            {romanji:"riouri", meaning: "the food, the cooking"}, {romanji:"nomimono", meaning: "drink"},
            {romanji:"supo-tsu", meaning: "sport"}, {romanji:"yakyuu", meaning: "baseball"},
            {romanji:"uta", meaning: "song"}, {romanji:"e", meaning: "picture"},
            {romanji:"ji", meaning: "word"}, {romanji:"kanji", meaning: "kanji"},
            {romanji:"kaze", meaning: "a cold"}, {romanji:"netsu", meaning: "a fever"},
            {romanji:"jikan", meaning: "time"}, {romanji:"youji", meaning: "busy work"},
            {romanji:"ha", meaning: "teeth"}, {romanji:"wakaru/wakarimasu", meaning: "understand"},
            {romanji:"aru/ arimasu", meaning: "have"}, {romanji:"yoku", meaning: "good"},
            {romanji:"takusan", meaning: "a lot"}, {romanji:"sukoshi", meaning: "a little"},
            {romanji:"zenzen", meaning: "totally not"}, {romanji:"hayaku", meaning: "fast"},
            {romanji:"hokani", meaning: "besides"}, {romanji:"zannen", meaning: "what a pity"},
        ]
    },
    {
        id:10,
        name:"I don't have a lover",
        cards:[
            {romanji:"iroiro", meaning: "many, diversity"}, {romanji:"inu", meaning: "dog"},
            {romanji:"neko", meaning: "cat"}, {romanji:"ki", meaning: "tree"},
            {romanji:"mono", meaning: "thing"}, {romanji:"hako", meaning: "box"},
            {romanji:"reizouko", meaning: "fridge"}, {romanji:"beddo", meaning: "bed"},
            {romanji:"kouen", meaning: "park"}, {romanji:"honya", meaning: "bookstore"},
            {romanji:"ike", meaning: "pond"}, {romanji:"chika", meaning: "basement"},
            {romanji:"ue", meaning: "above"}, {romanji:"shita", meaning: "below"},
            {romanji:"mae", meaning: "front"}, {romanji:"ushiro", meaning: "behind"},
            {romanji:"migi", meaning: "right"}, {romanji:"hidari", meaning: "left"},
            {romanji:"naka", meaning: "inside"}, {romanji:"soto", meaning: "outside"},
            {romanji:"tonati", meaning: "besides"}, {romanji:"chikaku", meaning: "near"},
            {romanji:"aida", meaning: "middle"}, {romanji:"aru/arimsu", meaning: "have, exist(for thing)"},
            {romanji:"iru/imasu", meaning: "have, exist(for animal)"},
        ]
    },
    {
        id:11,
        name:"Count people, things",
        cards:[
            {romanji:"aisukuri-mu", meaning: "icecream"}, {romanji:"hagaki", meaning: "postcard"},
            {romanji:"oku", meaning: "in the corner"}, {romanji:"hondana", meaning: "bookshelf"},
            {romanji:"ryou", meaning: "dormitory"}, {romanji:"inaka", meaning: "countryside"},
            {romanji:"gaikoku", meaning: "foreign country"}, {romanji:"doubutsu", meaning: "animal"},
            {romanji:"hirune", meaning: "noon sleep"}, {romanji:"hitotsu", meaning: "1"},
            {romanji:"futatsu", meaning: "2"}, {romanji:"mittsu", meaning: "3"},
            {romanji:"yotsu", meaning: "4"}, {romanji:"itsutsu", meaning: "5"},
            {romanji:"mutsu", meaning: "6"}, {romanji:"nanatsu", meaning: "7"},
            {romanji:"yatsu", meaning: "8"}, {romanji:"kokonotsu", meaning: "9"},
            {romanji:"too", meaning: "10"}, {romanji:"hitori", meaning: "1 person"},
            {romanji:"futari", meaning: "2 people"}, {romanji:"~nin", meaning: "~people"},
            {romanji:"~dai", meaning: "thing"}, {romanji:"dounokurai", meaning: "how long"},
            {romanji:"ikutsu", meaning: "how many"}, {romanji:"zenbude", meaning: "total"},
            {romanji:"yakimasu", meaning: "grill"}, {romanji:"tookuni", meaning: "faraway"},
            {romanji:"hitsuyou", meaning: "necessary"}, {romanji:"ryoushin", meaning: "parent"},
        ]
    }
  ]